### PR TITLE
#166237764 Deploy base application to Heroku

### PR DESCRIPTION
**Pull request by Nerocodes**
#### What does this PR do?
  - Adds app.json to generate review apps
  - Adds Procfile with start script for heroku

#### Description of Task to be completed?
  - Deploy base application to Heroku

#### How should this be manually tested?
  - Navigate to staging server [deferral-hello-books-staging](https://deferral-hello-books-staging.herokuapp.com/api/v1)
  - Navigate to production server [deferral-hello-books](https://deferral-hello-books.herokuapp.com/api/v1)

#### What are the relevant pivotal tracker stories?
[#166237764](https://www.pivotaltracker.com/story/show/166237764)

##### Production
deferral-hello-books

##### Staging
deferral-hello-books-staging

### CODE REVIEW

**Review by obayomi96 — COMMENTED** [review]
Great work @Nerocodes Thanks for deploying the base app to heroku. 
I think you need a new line in the app.json after line 11 and also in the procfile file.
I will also like you to enlighten me on the difference between heroku staging and the production. 
Thanks, awesome work!

**Review by obayomi96 — APPROVED** [review]

**Review by ayodejiAA — APPROVED** [review]
Looks good to go.

**Comment by Nerocodes** [comment]
> Great work @Nerocodes Thanks for deploying the base app to heroku.
> I think you need a new line in the app.json after line 11 and also in the procfile file.
> I will also like you to enlighten me on the difference between heroku staging and the production.
> Thanks, awesome work!

Thanks @obayomi96 staging is a replica of production. Staging is where changes are deployed to first and if nothing breaks it is then deployed to production. The pipeline process for deployment is as follows: 
```` review apps (created on each PR) -> staging -> production ````

**Comment by obayomi96** [comment]
> > Great work @Nerocodes Thanks for deploying the base app to heroku.
> > I think you need a new line in the app.json after line 11 and also in the procfile file.
> > I will also like you to enlighten me on the difference between heroku staging and the production.
> > Thanks, awesome work!
> 
> Thanks @obayomi96 staging is a replica of production. Staging is where changes are deployed to first and if nothing breaks it is then deployed to production. The pipeline process for deployment is as follows:
> `review apps (created on each PR) -> staging -> production`

Thanks for the breakdown. That's understandable now

**Review by tolulope-od — APPROVED** [review]
Great work @Nerocodes This looks good to me!

**Review by chialuka — APPROVED** [review]
And we're hosted live! Great job Nero.

**Pull request merged**
