### PR TITLE
#16623783 User can login with their social media accounts

### PR DESCRIPTION
**Pull request by chialuka**
#### What does this PR do?

- Enables user login with social accounts on Google, Facebook, and Twitter

#### Description of Task to be completed?

- Ensure users are provided access to login with their social accounts and will get a login token when they are authenticated

#### How should this be manually tested?

- Clone the repo and run `npm run test`

#### Any background context you want to provide?
This commit allows users access to use their social accounts to log in to their Hello Books accounts

#### What are the relevant pivotal tracker stories?
[#16623783
](https://www.pivotaltracker.com/story/show/166237835)

#### Screenshots (if appropriate)
Screenshot (123)

### CODE REVIEW

**Review by obayomi96 — APPROVED** [review]
This is well implemented and succinct. I can understand how the concept works by reviewing your PR. Well done @LukasChiama

**Review by ayodejiAA — APPROVED** [review]
Cool! I like how you implemented the feature neatly. Also, I learnt something new. Nice work!

**Review by chiboycalix — APPROVED** [review]
This has given me heads up on how to implement social media login. Thanks for your efforts. Your work is neat well done bro

**Review by Nerocodes — APPROVED** [review]
Awesome!! I am going to bookmark this PR. Great job!

**Review by abdulfatai360 — APPROVED** [review]

**Review by akpante3 — APPROVED** [review]

**Pull request merged**
