### PR TITLE
#166238087 User can view and delete favourite authors

### PR DESCRIPTION
**Pull request by ayodejiAA**
#### What does this PR do?
- Create endpoint for user to view list of favourite authors
- Create endpoint for user to delete author from favourite list
- Document the two features

#### Description of Task to be completed?
Have the following endpoints working 
- GET ```/api/v1/authors/favourites```
- PATCH ```/api/v1/authors/<authorId>/favourite```

#### How should this be manually tested?
The feature can be tested with any API testing application, like postman. It can as well be tested on the swagger documentation route.
- Clone the repository and checkout toft-user-view-delete-author-166238087. Add all required env variables.
-  Run ```npm run migration```, follow by ```npm start```, and use your API testing app to test the above API endpoints.

#### What are the relevant pivotal tracker stories?
[166238087](https://www.pivotaltracker.com/story/show/166238087)

#### Screenshots (if appropriate)
view fav

delete fav

### CODE REVIEW

**Review by chialuka — APPROVED** [review]
Bro, you're a rockstar! The Database join is cool. Great job man

**Comment by ayodejiAA** [comment]
> Bro, you're a rockstar! The Database join is cool. Great job man

Thanks @LukasChiama

**Review by chiboycalix — APPROVED** [review]
Nice work bro.

**Review by Nerocodes — APPROVED** [review]
Great job!

**Review by abdulfatai360 — APPROVED** [review]

**Review by obayomi96 — APPROVED** [review]
Very good work. Well done.

**Pull request merged**
