### PR TITLE
#166237762 Setup API documentation using swagger

### PR DESCRIPTION
**Pull request by tolulope-od**
#### What does this PR do?

- Sets up Swagger UI documentation route
- Updates README to reflect new documentation route
- Reorganizes project folder structure
- Refactors build script
- Adds Apache License

#### Description of Task to be completed?

Have the Swagger documentation working and visible on: 
`/api-docs`

#### How should this be manually tested?

Clone this branch, `cd` into it and do the following:
```bash
# install dependencies
$ npm install

# start the development server
$ npm run start-dev
```
Using a browser, visit the API documentation page at `localhost:4000/api-docs`

#### Any background context you want to provide?

This PR changes the folder structure of the project and also reconfigures the build script while also adding some necessary scripts required for the API documentation `json` file to be served in production.

#### What are the relevant pivotal tracker stories?

[#166237762](https://www.pivotaltracker.com/story/show/166237762)

#### Screenshots (if appropriate)
*API Documentation With Swagger UI*

Screenshot 2019-05-28 at 4 47 28 PM

### CODE REVIEW

**Review by obayomi96 — APPROVED** [review]
Good job with Swagger setup @tolulope-od . Thanks also for creating the server directory and refactoring the build and clean scripts. Well done.

**Review by ayodejiAA — APPROVED** [review]
Looks good. You have done well. @tolulope-od

**Review by abdulfatai360 — APPROVED** [review]
Well done @tolulope-od . PR LGTM

**Review by chialuka — APPROVED** [review]
Good job @tolulope-od, as usual.

**Pull request merged**
