### PR TITLE
#166237763 Integrate Coveralls code coverage service

### PR DESCRIPTION
**Pull request by ayodejiAA**
#### What does this PR do?
Integrate coveralls service into the project for code coverage

#### Description of Task to be completed?
- [x] Setup coveralls service for the project
- [x] Add coveralls badge to readme

#### How should this be manually tested?
- Currently, this integration has not been tested because Travis-Ci has not been integrated into the project. It will be tested once Travis is set up and build is passing.

#### What are the relevant pivotal tracker stories?
[#166237763](https://www.pivotaltracker.com/story/show/166237763)

### CODE REVIEW

**Review by obayomi96 — COMMENTED** [review]
Good job on setting up coveralls and the overall refactoring. Please, can you enlighten me on what effect the express.json makes compared to the bodyParser module as I've seen it before in your code but done understand fully? Well done!

**Comment by ayodejiAA** [comment]
> Good job on setting up coveralls and the overall refactoring. Please, can you enlighten me on what effect the express.json makes compared to the bodyParser module as I've seen it before in your code but done understand fully? Well done!

Thanks @obayomi96 Latest release of expressJs now has body-parser middleware included. So, I believe it will be redundant to install another package for that function. I hope this makes sense.

**Review by obayomi96 — APPROVED** [review]

**Comment by obayomi96** [comment]
> > Good job on setting up coveralls and the overall refactoring. Please, can you enlighten me on what effect the express.json makes compared to the bodyParser module as I've seen it before in your code but done understand fully? Well done!
> 
> Thanks @obayomi96 Latest release of expressJs now has body-parser middleware included. So, I believe it won't be redundant to install another package for that function.

Wow, that's good to know, I never knew they did. Thanks for the clarification. Good job.

**Review by chialuka — APPROVED** [review]
Good job @Xwebyna. Thumbs up

**Review by tolulope-od — APPROVED** [review]

**Review by Nerocodes — APPROVED** [review]
Great job

**Pull request merged**
